server:
 port: 8071
 
spring:
 datasource:
    url: jdbc:mysql://localhost:3306/db_oauth2?serverTimezone=America/Mexico_City&useSSL=false
    username: root
    password: cesar
    driver-class-name: com.mysql.cj.jdbc.Driver
 jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
logging:
  level:
    org:
    hibernate:
    sql: debug